### PR TITLE
Add initial support for VTech Laser Turbo XT

### PR DESCRIPTION
**Pull request by AtomicLunchbox**
Hacked in support for the VTech Laser Turbo XT. See docs [here](https://www.minuszerodegrees.net/manuals/VTech/VTech%20-%20Laser%20Turbo%20XT%20Series%20-%20Technical%20Reference%20Manual.pdf).

I've compiled this for 8088 and V20, but only tested with an 8088 on real hardware (I have a bare board). Also runs in PCem. Both seem to work correctly and turbo can be toggled on and off as expected with this patch.

First time writing assembly since college last century so apologies if the code is rough.

### CODE REVIEW

**Comment by 640-KB** [comment]
Awesome!  I'll give this a review shortly and definitely include it in the next revision.

Thanks for the contribution!

**Comment by 640-KB** [comment]
> Hacked in support for the VTech Laser Turbo XT. See docs [here](https://www.minuszerodegrees.net/manuals/VTech/VTech%20-%20Laser%20Turbo%20XT%20Series%20-%20Technical%20Reference%20Manual.pdf).
> 
> I've compiled this for 8088 and V20, but only tested with an 8088 on real hardware (I have a bare board). Also runs in PCem. Both seem to work correctly and turbo can be toggled on and off as expected with this patch.
> 
> First time writing assembly since college last century so apologies if the code is rough.

I just pushed some uncommitted changes I've had sitting for a while, which created a conflict with your PR.  I'll take a look at it and see if we can still merge it.

**Comment by AtomicLunchbox** [comment]
> I just pushed some uncommitted changes I've had sitting for a while, which created a conflict with your PR. I'll take a look at it and see if we can still merge it.

The conflicts look pretty trivial. I've resolved it on my fork and tested it on my board. Seems to work correctly.

**Comment by 640-KB** [comment]
Merged.  Thank you!

**Pull request merged**
